### ISSUE TITLE
lodash ist keine dependency, wird aber bei helpers/events.js importiert

### ISSUE THREAD

**Issue by christiansany** [unic/estatico-nou#42]

**Comment by backflip** [comment]
Thanks for the pointer, I had to add many missing dependencies: https://github.com/unic/estatico-nou/pull/44/commits/d8a35870aea4a3e2e3f4d2bdd78996323befe491
Possible downside of hoisting dependencies with Lerna. 

Btw: I had to switch back to hoisting after having issues with Webpack/Babel. The boilerplate wasn't able to properly run Babel anymore (possibly due to `@unic/estatico-webpack` being symlinked). Changing `babel-loader`, `@babel/preset-env` and friends to `require.resolve('babel-loader')` and `require.resolve('@babel/preset-env')`, respectively, solved most issues, but I don't think it's worth making the default config more complex just to make it work in a Lerna setup.
